# Generated by Django 5.2 on 2026-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
